# http://module-build.sourceforge.net/META-spec.html
name:         DTS
version:      0.06
version_from: lib/DTS.pm
installdirs:  site
requires:
    Carp:                          1.04
    Class::Accessor:               0.25
    Class::Publisher:              0.2
    DateTime:                      0.35
    Hash::Util:                    0.05
    Win32::OLE:                    0.1704
author: Alceu Rodrigues de Freitas Junior <arfreitas@cpan.org>
license: GNU GPL
distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
resources:
    license: http://www.gnu.org/licenses/old-licenses/gpl-2.0.html
    homepage: http://code.google.com/p/perldts/
    bugtracker: http://code.google.com/p/perldts/issues/list
    repository: http://code.google.com/p/perldts/source/browse/
